version: '3.9'

services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=pedro
      - DB_PASSWORD=123
      - DB=products_management
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=pedro
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=products_management
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pedro -d products_management"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - postgres_pedro:/var/lib/postgresql/data

volumes:
  postgres_pedro:
    driver: local
